### ISSUE TITLE
overflow

### ISSUE THREAD

**Issue by glycerine** [weinholt/conscheme#10]
Hey guys! This is a very, very cool project.  

Are bignums implimented? I did a quick check of factorial, and I see what looks like a bignum, but I also see overflow into negative numbers, yikes!

The expected answer for 120! is 6689502913449127057588118054090372586752746333138029810295671352301633557244962989366874165271984981308157637893214090552534408589408121859898481114389650005964960521256960000000000000000000000000000L
which was obtained with the python
~~~
 def recur_factorial(n):
   if n == 1:
       return n
   else:
      return n*recur_factorial(n-1)
~~~

~~~
$ ./conscheme -boot compiler/conscheme.image.pre-built
;; Con Scheme
;; Copyright (C) 2011, 2017 Göran Weinholt <goran@weinholt.se>
;; Copyright (C) 2011 Per Odlund <per.odlund@gmail.com>

#;0> (define (fact n) (if (zero? n) 1 (* n (fact (- n 1)))))
#;1> (fact 120)
-486257907331052715709238935398747208222169903540148891463936855367261459020919557136573214120000785664653529396019200000000000000
#;2> (fact 10)
3628800
#;3> (fact 20)
2432902008176640000
#;4> (fact 21)
-4249290049419214848
#;5> 
~~~

**Comment by weinholt** [comment]
Fixed on master, thanks! Let me know if you find any more bugs and hopefully they'll be fixed faster next time since I'm less busy now.
