### ISSUE TITLE
Is it possible to compile a script?

### ISSUE THREAD

**Issue by bentxt** [weinholt/conscheme#4]
After the installation, the next step would be the compile of an arbitrary script to bytecode. I couldn't figure it out and after a quick look in the source I'm not sure that even is implemented yet.

**Comment by weinholt** [comment]
It should be easy to add procedures for this. I'll do it tomorrow if I have time.

**Comment by weinholt** [comment]
I hope this fixes it for you.

**Comment by weinholt** [comment]
If you look at the dev branch there is now also support for loading a script from the command line.
