### ISSUE TITLE
Support of alternative clause syntax?

### ISSUE THREAD

**Issue by srctxt** [weinholt/conscheme#7]
hi,
I'm very happy that you keep on working on conscheme. The new plugin system looks interesting, I'm not aware of any other scheme that lets you dynamically load additional native functions.

The thing that I try to do here is a bit different thought. I'd like to use some of the functions of from pregexp.scm [1]. This is quite some complex scheme code with macros involved. 

I think there are some problems and a possible source that the "fat arrow" ("=>") is not supported. 

From Mit Schemes documentation [2]:

"Scheme supports an alternative clause syntax:

          (predicate => recipient)
     
where recipient is an expression. If predicate evaluates to a true value, then recipient is evaluated. Its value must be a procedure of one argument; this procedure is then invoked on the value of the predicate.

          (cond ((assv 'b '((a 1) (b 2))) => cadr)
                (else #f))                        
           ->  2
"

   [1]  https://ds26gte.github.io/pregexp/index.html
   [2]  https://www.gnu.org/software/mit-scheme/documentation/mit-scheme-ref/Conditionals.html

**Comment by weinholt** [comment]
The current macro system is very primitive, certainly something like syntax-rules or syntax-case is needed. I will fix the cond macro for now.

**Comment by weinholt** [comment]
Hope this gets you closer to using pregexp. Thanks for the bug report, please keep them coming!
